FROM maven:3.8.1-openjdk-17-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:17-jdk-slim
COPY --from=build /home/app/target/*.jar ./app.jar
COPY --from=build /home/app/ .
EXPOSE 8081
ENTRYPOINT java -jar ./app.jar
